predefined_positions:
  deploy:
    joint_names:
      - "girona500/bravo/joint1"
      - "girona500/bravo/joint2"
      - "girona500/bravo/joint3"
      - "girona500/bravo/joint4"
      - "girona500/bravo/joint5"
      - "girona500/bravo/joint6"
    positions: [0.0, 0.7853, -0.7853, 0.0, -1.57, 0.0]

predefined_trajectories:
  unfold:
    joint_names:
      - "girona500/bravo/joint1"
      - "girona500/bravo/joint2"
      - "girona500/bravo/joint3"
      - "girona500/bravo/joint4"
      - "girona500/bravo/joint5"
      - "girona500/bravo/joint6"
    points:
      - positions: [-1.57, -1.32, 0.0, -3.1, -1.22, 1.57]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 10.0, nsecs: 0.0}
      - positions: [-1.57, -1.32, 0.0, -3.1, -0.5, 1.57]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 20.0, nsecs: 0.0}
      - positions: [-1.57, -0.56, 0.0, -3.1, -0.59, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 35.0, nsecs: 0.0}
      - positions: [-1.57, 0.75, 0.0, -3.1, -0.94, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 50.0, nsecs: 0.0}
      - positions: [-1.57, 0.75, -0.72, -1.57, -1.57, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 65.0, nsecs: 0.0}


  fold:
    joint_names:
      - "girona500/bravo/joint1"
      - "girona500/bravo/joint2"
      - "girona500/bravo/joint3"
      - "girona500/bravo/joint4"
      - "girona500/bravo/joint5"
      - "girona500/bravo/joint6"
    points:
      - positions: [-1.57, 0.75, -0.72, -1.57, -1.57, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 15.0, nsecs: 0.0}
      - positions: [-1.57, 0.75, 0.0, -3.1, -0.94, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 30.0, nsecs: 0.0}
      - positions: [-1.57, -0.56, 0.0, -3.1, -0.59, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 45.0, nsecs: 0.0}
      - positions: [-1.57, -1.32, 0.0, -3.1, -0.5, 1.57]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 55.0, nsecs: 0.0}
      - positions: [-1.57, -1.32, 0.0, -3.1, -1.22, 1.57]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 65.0, nsecs: 0.0}
  
  home:
    joint_names:
      - "girona500/bravo/joint1"
      - "girona500/bravo/joint2"
      - "girona500/bravo/joint3"
      - "girona500/bravo/joint4"
      - "girona500/bravo/joint5"
      - "girona500/bravo/joint6"
    points:
      - positions: [-1.57, 0.75, -0.72, -1.57, -1.57, 1.57]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 25.0, nsecs: 0.0}
        
  look_down:
    joint_names:
      - "girona500/bravo/joint1"
      - "girona500/bravo/joint2"
      - "girona500/bravo/joint3"
      - "girona500/bravo/joint4"
      - "girona500/bravo/joint5"
      - "girona500/bravo/joint6"
    points:   
      - positions: [-0.10, -0.83, 0.90, 0.02, -2.95, 1.72, 0.00]
        velocities: [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: {secs: 15.0, nsecs: 0.0}

